### ISSUE TITLE
Not bulding. Pandas module required but not in requirements.txt

### ISSUE THREAD

**Issue by arlequin** [app-generator/django-materialpro-lite#3]
Hello,

I've tweaked the `pip` lines in the `Dockerfile` in order to reach my local proxy and put pip on track of getting internet access.
However, the build process is still requiering the Pandas module (which version...?) and it is not listed in `requirements.txt` file.

```
$ docker-compose up --build
Building appseed-app
Sending build context to Docker daemon  37.36MB
Step 1/9 : FROM python:3.9
 ---> 27ac39eccd1f
Step 2/9 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 48a2e21c5445
Step 3/9 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 4b54cdff9117
Step 4/9 : COPY requirements.txt .
 ---> Using cache
 ---> e07bdf7ecc82
Step 5/9 : RUN pip install  --proxy http://172.17.0.1:3128 --upgrade pip
 ---> Using cache
 ---> b51f83505ec2
Step 6/9 : RUN pip install --proxy http://172.17.0.1:3128 --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> 313621c33bf9
Step 7/9 : COPY . .
 ---> Using cache
 ---> 90dafda7bb45
Step 8/9 : RUN python manage.py migrate
 ---> Running in 5e3e671ca3fe
Traceback (most recent call last):
  File "//manage.py", line 22, in <module>
    main()
  File "//manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/core/urls.py", line 16, in <module>
    path("", include("apps.home.urls"))
  File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/home/urls.py", line 7, in <module>
    from apps.home import views
  File "/apps/home/views.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1
ERROR: Service 'appseed-app' failed to build : Build failed


$ cat requirements.txt
Django==3.2.16
asgiref==3.4.1
autopep8==1.6.0
dj-database-url==0.5.0
gunicorn==20.1.0
pycodestyle==2.8.0
pytz==2021.3
sqlparse==0.4.2
toml==0.10.2
whitenoise==5.3.0
django-environ==0.8.1
$
```

**Comment by arlequin** [comment]
My mistake. The error was clear: File "/apps/home/views.py", line 8 has pandas imported and this was modified by a developer outside the original code.
